{ Parsed from AppKit.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSAppleScriptExtensions.h }
{$ifdef CLASSES}

type
  NSAppleScript_NSExtensions = objccategory external name 'NSExtensions' (NSAppleScript)
    function richTextSource: NSAttributedString; message 'richTextSource';
  end;
{$endif}

