{ Parsed from AppKit.framework NSErrors.h }
{$ifdef EXTERNAL_SYMBOLS}
var
  NSTextLineTooLongException: NSExceptionName; cvar; external;
  NSTextNoSelectionException: NSExceptionName; cvar; external;
  NSWordTablesWriteException: NSExceptionName; cvar; external;
  NSWordTablesReadException: NSExceptionName; cvar; external;
  NSTextReadException: NSExceptionName; cvar; external;
  NSTextWriteException: NSExceptionName; cvar; external;
  NSPasteboardCommunicationException: NSExceptionName; cvar; external;
  NSPrintingCommunicationException: NSExceptionName; cvar; external;
  NSAbortModalException: NSExceptionName; cvar; external;
  NSAbortPrintingException: NSExceptionName; cvar; external;
  NSIllegalSelectorException: NSExceptionName; cvar; external;
  NSAppKitVirtualMemoryException: NSExceptionName; cvar; external;
  NSBadRTFDirectiveException: NSExceptionName; cvar; external;
  NSBadRTFFontTableException: NSExceptionName; cvar; external;
  NSBadRTFStyleSheetException: NSExceptionName; cvar; external;
  NSTypedStreamVersionException: NSExceptionName; cvar; external;
  NSTIFFException: NSExceptionName; cvar; external;
  NSPrintPackageException: NSExceptionName; cvar; external;
  NSBadRTFColorTableException: NSExceptionName; cvar; external;
  NSDraggingException: NSExceptionName; cvar; external;
  NSColorListIOException: NSExceptionName; cvar; external;
  NSColorListNotEditableException: NSExceptionName; cvar; external;
  NSBadBitmapParametersException: NSExceptionName; cvar; external;
  NSWindowServerCommunicationException: NSExceptionName; cvar; external;
  NSFontUnavailableException: NSExceptionName; cvar; external;
  NSPPDIncludeNotFoundException: NSExceptionName; cvar; external;
  NSPPDParseException: NSExceptionName; cvar; external;
  NSPPDIncludeStackOverflowException: NSExceptionName; cvar; external;
  NSPPDIncludeStackUnderflowException: NSExceptionName; cvar; external;
  NSRTFPropertyStackOverflowException: NSExceptionName; cvar; external;
  NSAppKitIgnoredException: NSExceptionName; cvar; external;
  NSBadComparisonException: NSExceptionName; cvar; external;
  NSImageCacheException: NSExceptionName; cvar; external;
  NSNibLoadingException: NSExceptionName; cvar; external;
  NSBrowserIllegalDelegateException: NSExceptionName; cvar; external;
  NSAccessibilityException: NSExceptionName deprecated 'Exceptions are no longer appropriate for indicating errors in accessibility API. Unexpected values should be handled through appropriate type checking.'; cvar; external;
{$endif}

