{ Parsed from AppKit.framework NSUserInterfaceLayout.h }
{$ifdef TYPES}
type
  NSUserInterfaceLayoutDirection = NSInteger;
  NSUserInterfaceLayoutDirectionPtr = ^NSUserInterfaceLayoutDirection;

const
  NSUserInterfaceLayoutDirectionLeftToRight = 0;
  NSUserInterfaceLayoutDirectionRightToLeft = 1;

type
  NSUserInterfaceLayoutOrientation = NSInteger;
  NSUserInterfaceLayoutOrientationPtr = ^NSUserInterfaceLayoutOrientation;

const
  NSUserInterfaceLayoutOrientationHorizontal = 0;
  NSUserInterfaceLayoutOrientationVertical = 1;
{$endif}

