{ Parsed from AppKit.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSUserInterfaceLayout.h }
{$ifdef TYPES}
type
  NSUserInterfaceLayoutDirection = NSInteger;
  NSUserInterfaceLayoutDirectionPtr = ^NSUserInterfaceLayoutDirection;

const
  NSUserInterfaceLayoutDirectionLeftToRight = 0;
  NSUserInterfaceLayoutDirectionRightToLeft = 1;

type
  NSUserInterfaceLayoutOrientation = NSInteger;
  NSUserInterfaceLayoutOrientationPtr = ^NSUserInterfaceLayoutOrientation;

const
  NSUserInterfaceLayoutOrientationHorizontal = 0;
  NSUserInterfaceLayoutOrientationVertical = 1;
{$endif}

