{ Parsed from WebKit.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/WebKit.framework/Headers/DOMHTMLFieldSetElement.h }

{$ifdef TYPES}
type
  DOMHTMLFieldSetElementPtr = ^DOMHTMLFieldSetElement;
{$endif}

{$ifdef CLASSES}

type
  DOMHTMLFieldSetElement = objcclass external (DOMHTMLElement)
  public
    function form: DOMHTMLFormElement; message 'form';
  end;
{$endif}

