{ Parsed from WebKit.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/WebKit.framework/Headers/DOMXPathException.h }
{$ifdef EXTERNAL_SYMBOLS}
var
  DOMXPathException: NSString deprecated 'in 10_4, 10_14'; cvar; external;
{$endif}

{$ifdef TYPES}
const
  DOM_INVALID_EXPRESSION_ERR = 51;
  DOM_TYPE_ERR = 52;
{$endif}

