{ Parsed from WebKit.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKMediaPlaybackState.h }
{$ifdef TYPES}
type
  WKMediaPlaybackState = NSUInteger;
  WKMediaPlaybackStatePtr = ^WKMediaPlaybackState;

const
  WKMediaPlaybackStateNone = 0;
  WKMediaPlaybackStatePaused = 1;
  WKMediaPlaybackStateSuspended = 2;
  WKMediaPlaybackStatePlaying = 3;
{$endif}

