{ Parsed from WebKit.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKPreviewActionItemIdentifiers.h }

{$if defined(TARGET_OS_IPHONE)}
{$ifdef EXTERNAL_SYMBOLS}
var
  WKPreviewActionItemIdentifierOpen: NSString deprecated 'This API will be replaced'; cvar; external;
  WKPreviewActionItemIdentifierAddToReadingList: NSString deprecated 'This API will be replaced'; cvar; external;
  WKPreviewActionItemIdentifierCopy: NSString deprecated 'This API will be replaced'; cvar; external;
  WKPreviewActionItemIdentifierShare: NSString deprecated 'This API will be replaced'; cvar; external;
{$endif}

{$endif}
