{ Parsed from ImageKit.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Headers/ImageKitDeprecated.h }
{$ifdef EXTERNAL_SYMBOLS}
var
  IKPictureTakerShowAddressBookPicture: NSString; cvar; external;
  IKPictureTakerShowEmptyPicture: NSString; cvar; external;
  IKPictureTakerCropAreaSizeKey: NSString; cvar; external;
{$endif}

