{ Parsed from CoreBluetooth.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/CoreBluetooth.framework/Headers/CBAdvertisementData.h }

{$ifdef EXTERNAL_SYMBOLS}
var
  CBAdvertisementDataLocalNameKey: NSString; cvar; external;
  CBAdvertisementDataTxPowerLevelKey: NSString; cvar; external;
  CBAdvertisementDataServiceUUIDsKey: NSString; cvar; external;
  CBAdvertisementDataServiceDataKey: NSString; cvar; external;
  CBAdvertisementDataManufacturerDataKey: NSString; cvar; external;
  CBAdvertisementDataOverflowServiceUUIDsKey: NSString { available in 10_9, 6_0 }; cvar; external;
  CBAdvertisementDataIsConnectable: NSString { available in 10_9, 7_0 }; cvar; external;
  CBAdvertisementDataSolicitedServiceUUIDsKey: NSString { available in 10_9, 7_0 }; cvar; external;
{$endif}

