{ Parsed from CoreBluetooth.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/CoreBluetooth.framework/Headers/CBPeripheralManagerConstants.h }
{$ifdef EXTERNAL_SYMBOLS}
var
  CBPeripheralManagerOptionShowPowerAlertKey: NSString { available in 10_9, 7_0 }; cvar; external;
  CBPeripheralManagerOptionRestoreIdentifierKey: NSString { available in 10_9, 7_0 }; cvar; external;
  CBPeripheralManagerRestoredStateServicesKey: NSString { available in 10_9, 7_0 }; cvar; external;
  CBPeripheralManagerRestoredStateAdvertisementDataKey: NSString { available in 10_9, 7_0 }; cvar; external;
{$endif}

