{ Parsed from CoreAudioKit.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/CoreAudioKit.framework/Headers/CAInterDeviceAudioViewController.h }

{$ifdef TYPES}
type
  CAInterDeviceAudioViewControllerPtr = ^CAInterDeviceAudioViewController;
{$endif}

{$if defined(__OBJC2__)}
{$ifdef CLASSES}

type
  CAInterDeviceAudioViewController = objcclass external (NSViewController)
  end;
{$endif}

{$endif}
