{ Parsed from CoreML.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/CoreML.framework/Headers/MLImageSizeConstraintType.h }
{$ifdef TYPES}
type
  MLImageSizeConstraintType = NSInteger;
  MLImageSizeConstraintTypePtr = ^MLImageSizeConstraintType;

const
  MLImageSizeConstraintTypeUnspecified = 0;
  MLImageSizeConstraintTypeEnumerated = 2;
  MLImageSizeConstraintTypeRange = 3;
{$endif}

