{ Parsed from SensorKit.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/SensorKit.framework/Headers/SRSensors+SRDeletionRecord.h }
{$ifdef CLASSES}

type
  NSString_SRDeletionRecord = objccategory external name 'SRDeletionRecord' (NSString)
    function sr_sensorForDeletionRecordsFromSensor: SRSensor; message 'sr_sensorForDeletionRecordsFromSensor';
  end;
{$endif}

